xwayland {
  force_zero_scaling = true
  create_abstract_socket = true
}

opengl {
	nvidia_anti_flicker = true
}

debug {
	overlay = false
}

dwindle {
    pseudotile = true
    preserve_split = true 
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1 
    disable_hyprland_logo = true
	vfr = false
	vrr = 1
	animate_manual_resizes = true
}

#---------------------------------------------------------------------------
# Workspace Configuration - For virtual-desktops plugin
# 2 monitors × 9 vdesks = 18 workspaces
# VDESK n → WS (n*2-1) on eDP-1, WS (n*2) on HDMI-A-1
#---------------------------------------------------------------------------
# workspace = 1, persistent:true
# workspace = 2, persistent:true
# workspace = 3, persistent:true
# workspace = 4, persistent:true
# workspace = 5, persistent:true
# workspace = 6, persistent:true
# workspace = 7, persistent:true
# workspace = 8, persistent:true
# workspace = 9, persistent:true
# workspace = 10, persistent:true
# workspace = 11, persistent:true
# workspace = 12, persistent:true
# workspace = 13, persistent:true
# workspace = 14, persistent:true
# workspace = 15, persistent:true
# workspace = 16, persistent:true
# workspace = 17, persistent:true
# workspace = 18, persistent:true

render {
    direct_scanout = 1 
    cm_enabled = true
    cm_auto_hdr = 1
    new_render_scheduling = true
	non_shader_cm = 1 
}


monitor=HDMI-A-1,1920x1080@100.00,0x0,1.00
monitor=eDP-1,1920x1080@120.00,1920x0,1.00

# env = LIBVA_DRIVER_NAME,nvidia
# env = XDG_SESSION_TYPE,wayland
# env = GBM_BACKEND,nvidia-drm
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia
# env = NVD_BACKEND,direct
# env = ELECTRON_OZONE_PLATFORM_HINT,auto
# env = MOZ_ENABLE_WAYLAND,1

# env = GDK_BACKEND,wayland,x11,*
# env = QT_QPA_PLATFORM,wayland;xcb
# env = CLUTTER_BACKEND,wayland
# env = XDG_CURRENT_DESKTOP,Hyprland
# env = XDG_SESSION_TYPE,wayland
# env = XDG_SESSION_DESKTOP,Hyprland

# env = QT_AUTO_SCREEN_SCALE_FACTOR,1
# env = QT_WAYLAND_DISABLE_WINDOWDECORATION,0
# env = QT_QPA_PLATFORMTHEME,kde
# env = GTK_THEME,oomox-hlocgtk
# env = HYPRCURSOR_THEME,Bibata-Modern-Amber
# env = HYPRCURSOR_SIZE,24
# env = XRCURSOR_THEME,Bibata-Modern-Amber
# env = XCURSOR_SIZE,24

# env = XDG_CONFIG_HOME,$HOME/.config
# env = XDG_CACHE_HOME,$HOME/.cache
# env = XDG_DATA_HOME,$HOME/.local/share
# env = XDG_STATE_HOME,$HOME/.local/state
# env = XDG_DATA_DIRS,/usr/local/share:/usr/share
# env = XDG_CONFIG_DIRS,/etc/xdg

